apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: geo-export
  description: |
    Handles exporting entire datasets which have a geo column as one of several
    formats. These formats currently include KML, KMZ and ESRI Shapefile. It
    takes a request to merge one or more dataset IDs in a particular format
    (kml, kmz, shp, geojson), asks soda-fountain for those datasets, and then
    expresses those datasets as layers in a manner applicable for the format.
  links:
  - title: OpsDoc
    url: "https://socrata.atlassian.net/wiki/spaces/ONCALL/pages/2158919953/OpsDoc+-+Geo-Export"
  - title: Teams Channel
    url: "https://teams.microsoft.com/l/channel/19%3Acc7bc69e4e1349c98d6de53dea8fcd97%40thread.tacv2/egress-q-and-a?groupId=102da3ef-c928-4a59-afe5-f0d51e6443dd&tenantId=7cc5f0f9-ee5b-4106-a62d-1b9f7be46118"
  annotations:
    github.com/project-slug: socrata-platform/geo-export
    backstage.io/techdocs-ref: dir:.
  tags:
    - scala
spec:
  type: service
  owner: egress
  lifecycle: production
