#!/bin/sh

set -ev
set -o pipefail

SERVER_JAR="$SERVER_ROOT/$SERVER_ARTIFACT"

if [ -n "$ECS_CONTAINER_METADATA_URI_V4" ]; then
    ARK_HOST="$(curl -sf "$ECS_CONTAINER_METADATA_URI_V4" | jq -r '.Networks[0].IPv4Addresses[0]')"
    export ARK_HOST
fi

/bin/env_parse /etc/${SERVER_CONFIG}.j2
/bin/env_parse /etc/${LOGBACK_CONFIG}.j2

# Duct tape to fix disk space issues caused
# by large exports - because shapefiles
# buffer to disk
ulimit -f "${MAX_FILE_SIZE_LIMIT_KB:-25000000}"

exec su socrata -c "exec /usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -Dconfig.file=/etc/${SERVER_CONFIG} \
    -Dlogback.configurationFile=/etc/${LOGBACK_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -jar $SERVER_JAR"
